### ISSUE TITLE
Not compatible with browser profiles

### ISSUE THREAD

**Issue by mi-skam** [TBM13/BrowserSearch#3] opened 2023-11-08 08:23 UTC
Copied version 1.2 into the Plugins repo, but after restarting Powertoys.exe I was greeted by a modal window, saying that the plugin is not compatible.

**Comment by TBM13** [comment] 2023-11-08 17:30
I'm using the plugin on that version of Powertoys and it works fine. Are you perhaps using the ARM64 version of PowerToys? I just noticed I haven't built the plugin for it, if that's the issue then I can send you an ARM64 build so you can test it.

Otherwise, please send a screenshot of the window.

**Comment by mi-skam** [comment] 2023-11-09 08:26
Nah, I am also on `x86_64`. Here is the requested screenshot

<img width="1298" alt="image" src="https://github.com/TBM13/BrowserSearch/assets/40042054/d0d65fb3-1e02-41af-b879-53b444ec7546">

**Comment by TBM13** [comment] 2023-11-09 11:44
Could you also attach the latest log? You can find them at `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs\`

**Comment by mi-skam** [comment] 2023-11-09 14:41
[2023-11-09.txt](https://github.com/TBM13/BrowserSearch/files/13309358/2023-11-09.txt)

**Comment by TBM13** [comment] 2023-11-09 16:05
The issue is that this plugin assumes that Chrome's history is located at `%LOCALAPPDATA%\Google\Chrome\User Data\Default\History` but that doesn't seem to be the case for you. If you are able to find where that file is in your computer, let me know.

**Comment by mi-skam** [comment] 2023-11-09 18:03
Ah, I see I suppose it's related to the use of profiles. I have history under my different profile names. 

<img width="54" alt="image" src="https://github.com/TBM13/BrowserSearch/assets/40042054/30c54157-e54a-41ac-b1ff-bda1e1d7d9b1">

So it's either 
`%LOCALAPPDATA%\Google\Chrome\User Data\Profile 4\History`
or
`%LOCALAPPDATA%\Google\Chrome\User Data\Profile 6\History`
`%LOCALAPPDATA%\Google\Chrome\User Data\Profile 7\History`

but no `Default` profile

**Comment by TBM13** [comment] 2023-11-09 18:12
That explains it. I will make the plugin search for the history file in those folders too and load history entries from all of them.

I may also add a setting to select the profile in case someone doesn't want to load the history from all of them.

**Comment by TBM13** [comment] 2023-12-07 15:21
Should be fixed on latest version

**Closed** 2023-12-17 00:13 UTC
