### ISSUE TITLE
I think it is broken on 0.76.2...

### ISSUE THREAD

**Issue by MeContoday** [TBM13/BrowserSearch#5] opened 2023-12-17 03:58 UTC
I am a Chinese.I use BrowserSearch on 0.76.2 is not work.I hope my grammar is correct...I hope you understand...I really need it!Please!

**Comment by TBM13** [comment] 2023-12-17 11:25
Can you send the latest log? It should be at `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs\0.76.2`

**Comment by ruoji1234** [comment] 2023-12-17 13:44
I also get a crash,this is latest log
[2023-12-17.txt](https://github.com/TBM13/BrowserSearch/files/13696297/2023-12-17.txt)

**Comment by aliuq** [comment] 2023-12-20 04:22
Same issue

**Comment by TBM13** [comment] 2023-12-20 21:09
> I also get a crash,this is latest log [2023-12-17.txt](https://github.com/TBM13/BrowserSearch/files/13696297/2023-12-17.txt)

Could you try this version of the plugin that has more debug logs and send the log again?
[BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip)



> Same issue

Send the latest log

**Comment by MeContoday** [comment] 2023-12-22 23:32
This is a new log(not work now!)
[2023-12-23.txt](https://github.com/TBM13/BrowserSearch/files/13757289/2023-12-23.txt)

**Comment by TBM13** [comment] 2023-12-24 22:42
> This is a new log(not work now!) [2023-12-23.txt](https://github.com/TBM13/BrowserSearch/files/13757289/2023-12-23.txt)

Thanks. Can you test if the issue is fixed with this version of the plugin?
[BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip)

**Comment by aliuq** [comment] 2023-12-25 03:06
@TBM13 Hi, I tried it, but not works on `google chrome dev`


[2023-12-25.txt](https://github.com/TBM13/BrowserSearch/files/13763625/2023-12-25.txt)

```bash
Unsupported/unrecognized default browser 'Google Chrome 开发者版'
```

**Comment by ruoji1234** [comment] 2023-12-25 04:15
> @TBM13 Hi, I tried it, but not works on `google chrome dev`
> 
> [2023-12-25.txt](https://github.com/TBM13/BrowserSearch/files/13763625/2023-12-25.txt)
> 
> ```shell
> Unsupported/unrecognized default browser 'Google Chrome 开发者版'
> ```

it works, I work it on edge.
this is the latest log
[Uploading 2023-12-25.txt…]()

**Comment by TBM13** [comment] 2023-12-27 23:58
> @TBM13 Hi, I tried it, but not works on `google chrome dev`
> 
> [2023-12-25.txt](https://github.com/TBM13/BrowserSearch/files/13763625/2023-12-25.txt)
> 
> ```shell
> Unsupported/unrecognized default browser 'Google Chrome 开发者版'
> ```

Currently non-stable Chrome/Edge variants aren't supported. Trying to figure out a way to detect they are the default browser as it seems the browser name can change depending on the language as it's in your case

**Comment by JupiterOdyssey** [comment] 2024-01-15 17:21
> > This is a new log(not work now!) [2023-12-23.txt](https://github.com/TBM13/BrowserSearch/files/13757289/2023-12-23.txt)
> 
> Thanks. Can you test if the issue is fixed with this version of the plugin? [BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip)

I encountered the same problem. I finally used [BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip) instead of [v1.3](https://github.com/TBM13/BrowserSearch/releases/tag/v1.3), and solved the problem.

Thank you very much🤗!

**Comment by TBM13** [comment] 2024-01-15 19:01
> > > This is a new log(not work now!) [2023-12-23.txt](https://github.com/TBM13/BrowserSearch/files/13757289/2023-12-23.txt)
> > 
> > 
> > Thanks. Can you test if the issue is fixed with this version of the plugin? [BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip)
> 
> I encountered the same problem. I finally used [BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip) instead of [v1.3](https://github.com/TBM13/BrowserSearch/releases/tag/v1.3), and solved the problem.
> 
> Thank you very much🤗!

Thanks for confirming

**Closed** 2024-01-15 19:20 UTC

**Comment by JupiterOdyssey** [comment] 2024-01-16 01:03
> > > This is a new log(not work now!) [2023-12-23.txt](https://github.com/TBM13/BrowserSearch/files/13757289/2023-12-23.txt)
> > 
> > 
> > Thanks. Can you test if the issue is fixed with this version of the plugin? [BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip)
> 
> I encountered the same problem. I finally used [BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip) instead of [v1.3](https://github.com/TBM13/BrowserSearch/releases/tag/v1.3), and solved the problem.
> 
> Thank you very much🤗!

I made a mistake, I used [BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip) , not [BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip). I’m not sure if [BrowserSearch-debug.zip](https://github.com/TBM13/BrowserSearch/files/13732552/BrowserSearch-debug.zip) is valid, but [BrowserSearch-test.zip](https://github.com/TBM13/BrowserSearch/files/13762956/BrowserSearch-test.zip) definitely works.

PowerToys version: 0.77.0.0
