### ISSUE TITLE
Browser "Vivaldi" not support

### ISSUE THREAD

**Issue by AndreasWeste** [TBM13/BrowserSearch#17] opened 2024-04-23 19:15 UTC
Messagebox: Browser "Vivaldi" not supported, every time at system launch.

Windows 10 Version 22H2 (Build 19045.4291) 
Powertoys 0.80.1
Vivaldi 6.6.3271.61 (Stable channel)

**Comment by TBM13** [comment] 2024-04-23 23:59
Can you send the latest log located at %localappdata%\Microsoft\PowerToys\PowerToys Run\Logs\0.80.1.0?

**Comment by AndreasWeste** [comment] 2024-04-27 10:35
The issue fixed itself after a few days. Logfiles are very similar before and after. I recommend closing this Issue.
[2024-04-22.txt](https://github.com/TBM13/BrowserSearch/files/15137885/2024-04-22.txt)
[2024-04-23.txt](https://github.com/TBM13/BrowserSearch/files/15137886/2024-04-23.txt)
[2024-04-24.txt](https://github.com/TBM13/BrowserSearch/files/15137887/2024-04-24.txt)
[2024-04-25.txt](https://github.com/TBM13/BrowserSearch/files/15137888/2024-04-25.txt)

**Comment by TBM13** [comment] 2024-04-27 16:18
I believe I know what the issue is. Hopefully it'll be fixed on the next version

**Comment by TBM13** [comment] 2024-05-09 19:59
Should be fixed on the latest release. Let me know if it happens again.

**Closed by TBM13** 2024-05-09 19:59 UTC
